<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">
	<title>Análisis de componentes principales</title>

	<!-- mobile responsive meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="El espacio perfecto para Biólogos y R">
	
	<meta name="author" content="&lt;/R Biólogos&gt;">
	<meta name="generator" content="Hugo 0.121.1">

	<!-- plugins -->
	
	<link rel="stylesheet" href="https://rbiologos.github.io/plugins/bootstrap/bootstrap.min.css">
	
	<link rel="stylesheet" href="https://rbiologos.github.io/plugins/themify-icons/themify-icons.css">
	
	<link rel="stylesheet" href="https://rbiologos.github.io/plugins/magnific-popup/magnific-popup.css">
	
	<link rel="stylesheet" href="https://rbiologos.github.io/plugins/slick/slick.css">
	
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Anaheim%7cQuattrocento&#43;Sans:400,700&amp;display=swap">
	

	<!-- Main Stylesheet -->
	
	<link rel="stylesheet" href="https://rbiologos.github.io/css/style.min.css" media="screen">

	<!-- Custom stylesheet - for your changes -->
	
  <link rel="stylesheet" href="https://rbiologos.github.io/css/custom.min.css" media="screen">

	<!--Favicon-->
	<link rel="shortcut icon" href="https://i.ibb.co/4RJbzB6/2.png" type="image/x-icon">
	<link rel="icon" href="https://i.ibb.co/4RJbzB6/2.png" type="image/x-icon">

	
	<!-- Global Site Tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-N49JEEK9KF"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'G-N49JEEK9KF');
	</script>
	

</head>


<body id="body" data-spy="scroll" data-target=".navbar" data-offset="55">
  <div id="content">
    
<!-- preloader start -->
<div class="preloader">
  
  <img src="https://i.ibb.co/FxCR4MP/loader.gif" alt="preloader" width="300">
  
</div>
<!-- preloader end -->



<section class="sticky-top navigation">
	<div class="container">
		<nav class="navbar navbar-expand-lg navbar-dark">
			<a class="navbar-brand p-0" href="/">
				
				<img class="lozad" data-src="https://i.ibb.co/4RJbzB6/2.png" alt="R Biólogos" height="42">
				
			</a>

			<button class="navbar-toggler rounded-0" type="button" data-toggle="collapse" data-target="#navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navigation">
				<ul class="navbar-nav ml-auto">
					
					<li class="nav-item">
            <a class="nav-link" href="/#https://rbiologos.github.io/">Inicio</a>
					</li>
					
					
					<li class="nav-item">
            <a class="nav-link" href="/#blog">Blog</a>
					</li>
					
					
					<li class="nav-item">
            <a class="nav-link" href="/#team">Equipo</a>
					</li>
					
					
					<li class="nav-item">
            <a class="nav-link" href="/#feature">¿Qué hacemos?</a>
					</li>
					
					
					<li class="nav-item">
            <a class="nav-link" href="/#contact">Contacto</a>
					</li>
					
					
				</ul></div>
				
				
				<select id="select-language" onchange="location = this.value;">
					
					
					
					
					
					
					
					
					<option id="es" value="https://rbiologos.github.io/blog/a018/" selected>ES
					</option>
					
					
					
					
					
					
					
					
				</select>
				
			
			<script>
  (function() {
    var id = '06c75f9c-882f-11eb-a152-0242ac130002';
    var ci_search = document.createElement('script');
    ci_search.type = 'text/javascript';
    ci_search.async = true;
    ci_search.src = 'https://cse.expertrec.com/api/js/ci_common.js?id=' + id;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(ci_search, s);
  })();
</script><ci-search></ci-search>
		</nav>
	</div>
</section>


<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2 text-center">
        <h1>Análisis de componentes principales</h1>
        <ul class="list-inline mb-50">
          <li class="list-inline-item"><a href="/author/david-vanegas/">David Vanegas</a></li>
          <li class="list-inline-item">miércoles, ene. 3, 2024</li>
        </ul>
        <img class="img-fluid mb-50 lozad" data-src="https://i.ibb.co/VgPKSPL/ES.png" alt="blog-image">
      </div>
      <div class="col-lg-8 offset-lg-2">
        <div class="post-single-content">
          


<p>El <strong><em>Análisis de componentes principales</em></strong> es una técnica muy útil cuando tenemos datos que contienen múltiples variables, y que queremos reducir con el fin de quedarnos solo con lo esencial.</p>
<center>
<img src="https://i.ibb.co/FDBH0jr/Aot1.gif" width="350" />
</center>
<p></br></p>
<div id="contenido-del-post" class="section level1">
<h1>Contenido del post</h1>
<ul>
<li><a href="#id_1">Introducción</a></li>
<li><a href="#id_2">Código en R</a>
<ul>
<li><a href="#id_3">Análisis de correlación</a></li>
<li><a href="#id_4">Visualización de los componentes principales</a>
<ul>
<li><a href="#id_5">Scree plot</a></li>
<li><a href="#id_6">Biplot de los atributos</a></li>
</ul></li>
<li><a href="#id_7">Calcular cargas factoriales</a>
<ul>
<li><a href="#id_8">Contribución de cada variable</a></li>
<li><a href="#id_9">Biplot combinado con cos2</a></li>
</ul></li>
</ul></li>
<li><a href="#id_10">Resumen</a></li>
<li><a href="#id_11">Literatura</a></li>
<li><a href="#id_12">Más información</a></li>
</ul>
</div>
<div id="introducción" class="section level1">
<h1>Introducción</h1>
<p><a name="1"></a></p>
<p>El <strong><em>Análisis de componentes principales</em></strong>, o <em>PCA</em> por sus siglas en inglés, es una técnica muy útil cuando tenemos que trabajar con datos que tienen muchas variables o características. Por ejemplo, imagina que estás estudiando un ecosistema y tienes datos de la temperatura, la humedad, la vegetación, el viento, el riesgo de incendios, etc. ¿Cómo puedes visualizar toda esa información en un solo gráfico? ¿Cómo puedes saber qué variables son las más importantes o las que más influyen en el comportamiento del ecosistema? Aquí es donde entra el PCA.</p>
<p>El PCA es una forma de reducir la dimensionalidad de los datos, es decir, de simplificarlos para quedarnos solo con lo esencial. Lo que hace el PCA es encontrar unas nuevas variables, llamadas <strong><em>componentes principales</em></strong>, que son combinaciones lineales de las variables originales, que tienen la propiedad de capturar la mayor parte de la variación o la información de los datos. Así, podemos representar los datos en un espacio de menor dimensión, por ejemplo, en un plano bidimensional o en un espacio tridimensional. Esto nos puede dar pistas sobre qué variables son las que determinan el fenómeno del sistema que estamos estudiando. Por ejemplo, si la primera componente principal está muy relacionada con la temperatura y la humedad, podemos inferir que estas variables son las que más afectan al ecosistema.</p>
<p>En resumen, el PCA es una técnica muy poderosa y versátil que nos permite simplificar y entender mejor nuestros datos. Si quieres aprender más sobre cómo aplicar el PCA a tus datos, te invito a seguir leyendo este blog, te explicaremos cómo hacer el PCA paso a paso en R y cómo interpretar los resultados.</p>
<center>
<img src="https://i.ibb.co/x2FLKG7/retumbar.gif" width="350" />
</center>
<p></br></p>
</div>
<div id="código-en-r" class="section level1">
<h1>Código en R</h1>
<p><a name="2"></a></p>
<p>Para aprender a hacer un PCA en R usaremos un conjunto de datos llamado <strong><em>bioenv</em></strong>, obtenido del blog <a href="https://bio723-class.github.io/Bio723-book/principal-components-analysis.html#principal-components-analysis-in-r">Principal Components Analysis</a>.</p>
<p>Como primera medida a tomar, conoceremos las paqueterías de R que vamos a utilizar en este ejercicio.</p>
<pre class="r"><code>library(readxl)
library(GGally)
library(factoextra)
library(corrplot)</code></pre>
<p>Esta base de datos, es un conjunto de variables observadas en lugares del fondo marino, en un estudio de biología marina: el primero es un conjunto de variables biológicas, el recuento de cinco grupos de especies, y el segundo es un conjunto de cuatro variables ambientales. Los grupos de especies se abrevian como “a” hasta “e”. Las variables ambientales son “contaminación”, un índice compuesto de contaminación que combina mediciones de concentraciones de metales pesados e hidrocarburos; profundidad, la profundidad en metros del fondo marino donde se tomó la muestra; “temperatura”, la temperatura del agua en el punto de muestreo; y ‘sedimento’, una clasificación del sustrato de la muestra en una de tres categorías de sedimentos.</p>
<center>
<img src="https://i.ibb.co/0fmB3RD/wall-titans.gif" width="350" />
</center>
<p></br></p>
<p>Para el ejercicio que realizaremos únicamente analizaremos las variables del recuendo de los cinco grupos de especies. Así, comenzaremos leyendo nuestra base de datos desde nuestro repositorio en <strong>GITHUB</strong>, y filtraremos la información que necesitemos.</p>
<pre class="r"><code>## Esta es una base de datos que se encuentra en línea, por ello, 
## debemos guardar los datos en una variable
bioenv_data &lt;- read.csv(&#39;https://raw.githubusercontent.com/RBiologos/Docs/main/bioenv.csv&#39;, sep = &#39;;&#39;)

## Veamos un poco de nuestros datos
head(bioenv_data)</code></pre>
<pre><code>##   Site  a  b  c  d e Pollution Depth Temperature Sediment
## 1  s1   0  2  9 14 2       4.8    72         3.5        S
## 2  s2  26  4 13 11 0       2.8    75         2.5        C
## 3  s3   0 10  9  8 0       5.4    59         2.7        C
## 4  s4   0  0 15  3 0       8.2    64         2.9        S
## 5  s5  13  5  3 10 7       3.9    61         3.1        C
## 6  s6  31 21 13 16 5       2.6    94         3.5        G</code></pre>
<pre class="r"><code>## Eliminamos variables que no necesitamos
bioenv &lt;- bioenv_data[, 2:6]</code></pre>
<p>Ahora, hagámos una breve incursión por la naturaleza de nuestros datos y su comportamiento. Para ello, analizaremos su media y varianza, con el fin de encontrar posibles problemas para el análisis de nuestro PCA.</p>
<pre class="r"><code>## Análisis de media
apply(X = bioenv, MARGIN = 2, FUN = mean)</code></pre>
<pre><code>##         a         b         c         d         e 
## 13.466667  8.733333  8.400000 10.900000  2.966667</code></pre>
<pre class="r"><code>## Análisis de varianza
apply(X = bioenv, MARGIN = 2, FUN = var)</code></pre>
<pre><code>##         a         b         c         d         e 
## 157.63678  83.44368  73.62759  44.43793  15.68851</code></pre>
<p>Como observamos, el promedio de los datos muestra que no hay estandarización entre las variables, mientras que variables como <em>Depth</em> quien posee valores muy altos en comparación con las otra variables.Además podemos observar que en términos de la varianza, la variable <em>Depth</em> sigue teniendo el mismo comportamiento. Si no se estandarizan las variables para que tengan media cero y desviación estándar 1 antes de realizar el estudio PCA, la variable <em>Depth</em> dominará la mayoría de las componentes principales.</p>
<div id="análisis-de-correlación" class="section level2">
<h2>Análisis de correlación</h2>
<p><a name="3"></a></p>
<p>En el primer paso para el entendimiento de nuestros datos, haremos una correlación, la cual suele usarse para analizar la correlación de las variables que tenemos previamente al análisis de PCA. Se puede calcular usando la función <em><res>ggpairs()</em></res> del paquete <em><res>GGally</res></em>.</p>
<pre class="r"><code>## Ejecutamos el código para la correlación de las variables
corr &lt;- ggpairs(bioenv)

## Graficamos dicho resultado
corr</code></pre>
<p><img src="https://rbiologos.github.io/blog/a018/index.es_files/figure-html/unnamed-chunk-4-1.png" width="100%" /></p>
<p>El resultado de la matriz de correlación se puede interpretar de la siguiente manera:</p>
<ul>
<li>Cuanto mayor sea el valor, más correlacionadas positivamente estarán las dos variables.</li>
<li>Cuanto más cerca esté el valor de -1, más negativamente estarán correlacionados.</li>
</ul>
<p>Así podemos decir que las variables tienen una correlación alta, siendo la variable <em>a</em> y <em>b</em> poseen los mayores valores. Cabe resaltar que la variable <em>c</em> tiene los valores más bajos de correlación en comparación con las otras variables.</p>
<pre class="r"><code>## Realizamos nuestro análisis PCA
pca &lt;- prcomp(bioenv, center=TRUE, retx=TRUE)

## Visualizamos el resumen de los resultados
summary(pca)</code></pre>
<pre><code>## Importance of components:
##                            PC1    PC2    PC3     PC4     PC5
## Standard deviation     14.8653 8.8149 6.2193 5.03477 3.48231
## Proportion of Variance  0.5895 0.2073 0.1032 0.06763 0.03235
## Cumulative Proportion   0.5895 0.7968 0.9000 0.96765 1.00000</code></pre>
<p>Vemos que aproximadamente el <strong><em>58.95 %</em></strong> de la variación en los datos es capturada por el primer componente (PC1) y aproximadamente el <strong><em>90.00 %</em></strong> por los tres primeros componentes (PC3).</p>
<p>Comparemos los valores devueltos por el PCA con los que obtendríamos si realizáramos un análisis propio de la matriz de covarianza que corresponde a nuestros datos. De esta manera, procederemos a ver nuestros resultados</p>
<pre class="r"><code>pca</code></pre>
<pre><code>## Standard deviations (1, .., p=5):
## [1] 14.865306  8.814912  6.219250  5.034774  3.482308
## 
## Rotation (n x k) = (5 x 5):
##           PC1         PC2         PC3         PC4         PC5
## a  0.81064462  0.07052882 -0.53108427  0.18442140 -0.14771336
## b  0.51264394 -0.27799671  0.47711910 -0.63418946  0.17342177
## c -0.16235135 -0.88665551 -0.40897655 -0.01149647  0.14173943
## d  0.22207108 -0.31665237  0.56250980  0.72941223 -0.04422938
## e  0.06616623  0.17696554 -0.08141111  0.17781482  0.96231977</code></pre>
</div>
<div id="visualización-de-los-componentes-principales" class="section level2">
<h2>Visualización de los componentes principales</h2>
<p><a name="4"></a></p>
<p>El análisis previo de la matriz de carga proporcionó una buena comprensión de la relación entre cada uno de los dos primeros componentes principales y los atributos de los datos. Sin embargo, puede que no resulte atractivo visualmente. Para entender mejor estos resultados hay un par de estrategias de visualización estándar que pueden ayudar al investigador a obtener información sobre los datos.</p>
<center>
<img src="https://i.ibb.co/xJk1PKk/At2.gif" width="350" />
</center>
<p></br></p>
<div id="scree-plot" class="section level3">
<h3>Scree Plot</h3>
<p><a name="5"></a></p>
<p>Una de estas herramientas se utiliza para visualizar la importancia de cada componente principal y se puede utilizar para determinar la cantidad de componentes principales que se deben mantener en un análisis de componentes principales (PCA). El <strong>Scree Plot</strong> se puede generar usando la función <em><res>fviz_eig()</res></em>.</p>
<pre class="r"><code>fviz_eig(pca, addlabels = TRUE)</code></pre>
<p><img src="https://rbiologos.github.io/blog/a018/index.es_files/figure-html/unnamed-chunk-7-1.png" width="100%" /></p>
<p>Este gráfico muestra los valores propios en una curva descendente, de mayor a menor. Los dos primeros componentes pueden considerarse los más significativos ya que contienen casi el <strong><em>90 %</em></strong> de la información total de los datos.</p>
</div>
<div id="biplot-de-los-atributos" class="section level3">
<h3>Biplot de los atributos</h3>
<p><a name="6"></a></p>
<p>De manera paralela podemos utilizar el gráfico de biplot, con el cual es posible visualizar las similitudes y diferencias entre las muestras, y además muestra el impacto de cada atributo en cada uno de los componentes principales.</p>
<pre class="r"><code># Graph of the variables
fviz_pca_var(pca, col.var = &quot;black&quot;)</code></pre>
<p><img src="https://rbiologos.github.io/blog/a018/index.es_files/figure-html/unnamed-chunk-8-1.png" width="100%" /></p>
<p>Del gráfico anterior se pueden observar tres datos principales.</p>
<ul>
<li><p>En primer lugar, todas las variables que se agrupan están en cierto grado de correlación positivamente entre sí, y ese es el caso, por ejemplo, de las variables <strong>a</strong>, <strong>b</strong> y <strong>d</strong> que tienen una correlación positiva entre sí.</p></li>
<li><p>Entonces, cuanto mayor sea la distancia entre la variable y el origen, mejor representada estará esa variable. Según el biplot, la variable <strong>a</strong> tiene una magnitud mayor en comparación con las variables <strong>b</strong> y <strong>d</strong> y, por lo tanto, están bien representados en comparación con la variable <strong>a</strong>.</p></li>
<li><p>Finalmente, las variables que están correlacionadas negativamente se muestran en los lados opuestos del origen del biplot, como la variable <strong>c</strong>.</p></li>
</ul>
<p>Igualmente, a partir del biplot podemos inferir que la variable <strong>a</strong> está altamente correlacionada con PC1, pero solo débilmente asociada con PC2. Por el contrario, la variable <strong>c</strong> está fuertemente correlacionada con PC2 pero sólo débilmente con PC1. También podemos aproximar las correlaciones entre las variables mismas; por ejemplo, <strong>b</strong> y <strong>d</strong> están bastante fuertemente correlacionadas, pero débilmente correlacionadas con <strong>c</strong>.</p>
<center>
<img src="https://i.ibb.co/wrMJ5SK/at3.gif" width="350" />
</center>
<p></br></p>
</div>
</div>
<div id="calcular-cargas-factoriales" class="section level2">
<h2>Calcular cargas factoriales</h2>
<p><a name="7"></a></p>
<p>Las cargas factoriales representan la fuerza de la relación entre las variables observadas y los factores subyacentes. Cabe resaltar que un error común es interpretar las cargas factoriales como correlaciones entre las variables, para poder entender mejor la importancia y los errores más comunes puedes visitar el sitio <a href="https://fastercapital.com/es/contenido/Carga-factorial--decodificacion-de-cargas-factoriales-en-el-modelo-multifactor.html#:~:text=los%20m%C3%A1s%20desafiantes.-,Las%20cargas%20factoriales%20representan%20la%20fuerza%20de%20la%20relaci%C3%B3n%20entre,como%20correlaciones%20entre%20las%20variables">Carga factorial decodificacion de cargas factoriales en el modelo multifactor</a>. Ahora si, calculemos las “cargas factoriales” asociadas a la PC.</p>
<pre class="r"><code>V &lt;- pca$rotation # eigenvectors
L &lt;- diag(pca$sdev) # diag mtx w/sqrts of eigenvalues on diag.

loadings &lt;- V %*% L
loadings</code></pre>
<pre><code>##         [,1]       [,2]       [,3]        [,4]       [,5]
## a 12.0504801  0.6217053 -3.3029460  0.92852016 -0.5143835
## b  7.6206090 -2.4505164  2.9673232 -3.19300085  0.6039081
## c -2.4134024 -7.8157898 -2.5435276 -0.05788214  0.4935804
## d  3.3011545 -2.7912626  3.4983893  3.67242602 -0.1540203
## e  0.9835813  1.5599356 -0.5063161  0.89525751  3.3510942</code></pre>
<p>La magnitud de las cargas factoriales es en lo que desea centrarse. Por ejemplo, las especies <strong>a</strong> y <strong>b</strong> contribuyen más al primer PC, mientras que la especie <strong>c</strong> tiene la mayor influencia en el PC2.</p>
<div id="contribución-de-cada-variable" class="section level3">
<h3>Contribución de cada variable</h3>
<p><a name="8"></a></p>
<p>El objetivo de la esta visualización es determinar cuánto está representada cada variable en un componente determinado. Esta calidad de representación se llama Cos2 y corresponde al coseno cuadrado, y se calcula utilizando la función <em><res>fviz_cos2</res></em>.</p>
<p>Un valor bajo significa que la variable no está perfectamente representada por ese componente. Por otro lado, un valor alto significa una buena representación de la variable en ese componente.</p>
<pre class="r"><code>## Contribución de las variables al PC1 y PC2
fviz_cos2(pca, choice = &quot;var&quot;, axes = 1:2)</code></pre>
<p><img src="https://rbiologos.github.io/blog/a018/index.es_files/figure-html/unnamed-chunk-10-1.png" width="100%" /></p>
<p>Igualmente, podemos crear un mapa de factores a partir igualmente del cos2 (coseno cuadrado, coordenadas al cuadrado), a partir de la paquetería <em><res>corrplot</res></em> de la siguiente manera:</p>
<pre class="r"><code>## Extraemos los datos del PCA para graficar
var &lt;- get_pca_var(pca)

## Generamos el gráfico de correlación
corrplot(var$contrib, is.corr=FALSE)  </code></pre>
<p><img src="https://rbiologos.github.io/blog/a018/index.es_files/figure-html/unnamed-chunk-11-1.png" width="100%" /></p>
<p>En los códigos y gráficos anteriores se calculó el valor del coseno cuadrado para cada variable con respecto a los dos primeros componentes principales.</p>
<p>Así, en las ilustraciones en general, las variables <strong>a</strong>, <strong>b</strong> y <strong>c</strong> son las tres variables principales con el cos2 más alto y, por lo tanto, son las que más contribuyen a PC1 y PC2. Particularmente las variables <strong>a</strong> y <strong>b</strong> contribuyen en mayor medida al PC1 y la variable <strong>c</strong> contribuye en mayor manera al PC2, en relación a los otras variables.</p>
<center>
<img src="https://i.ibb.co/ZMswqMq/at4.gif" width="350" />
</center>
<p></br></p>
</div>
<div id="biplot-combinado-con-cos2" class="section level3">
<h3>Biplot combinado con cos2</h3>
<p><a name="9"></a></p>
<p>Los dos últimos enfoques de visualización son biplot e importancia de las variables, los cuales se pueden combinar para crear un único biplot, donde las variables con puntuaciones de cos2 similares tendrán colores similares. Esto se logra ajustando la función <em><res>fviz_pca_var</res></em> de la siguiente manera</p>
<pre class="r"><code>fviz_pca_var(pca, col.var = &quot;cos2&quot;,
            gradient.cols = c(&quot;black&quot;, &quot;blue&quot;, &quot;green&quot;),
            repel = TRUE)</code></pre>
<p><img src="https://rbiologos.github.io/blog/a018/index.es_files/figure-html/unnamed-chunk-12-1.png" width="100%" /></p>
<p>Del gráfico biplot anterior entonces podemos concluir que:</p>
<ul>
<li>Las variables con alto cos2 están coloreadas en verde: <strong>a</strong>.</li>
<li>Ls variavles con medio cos2 tienen un color azul: <strong>b</strong> y <strong>c</strong>.</li>
<li>Finalmente, las variables de bajo cos2 tienen color negro: <strong>d</strong> y <strong>e</strong>.</li>
</ul>
</div>
</div>
</div>
<div id="resumen" class="section level1">
<h1>Resumen</h1>
<p><a name="10"></a></p>
<p>Esta lectura ha cubierto una parte de qué es el Análisis de componentes principales y su importancia en el análisis de datos, a partir de datos biológicos. Así mismo, pudimos aprender algunas técnicas visuales para su entendimiento como el biplot y los resultados del cos2, con el fin de entender la relación de las distintas variables.</p>
<p>Como siempre, desde RBiólogos esperamos que este tipo de post nos ayuden a entrar en este fascinante mundo. Cabe resaltar que es apenas una aproximación a toda la matemática y biología que hay detras de ello. Por eso, te invitamos a que puedas profundizar más en este tipo de análisis para poder tomar las mejores decisiones en tu proyecto.</p>
<p>Así mismo, recordar que la estadística y matemática deben ir acompañadas por una buena discusión biológica, donde se pueda hacer ciencia de excelente calidad.</p>
<center>
<img src="https://i.ibb.co/DR0Zzk5/eren-jaeger-eren.gif" width="350" />
</center>
<p></br></p>
</div>
<div id="literatura" class="section level1">
<h1>Literatura</h1>
<p><a name="11"></a></p>
<ul>
<li><p><a href="https://www.datacamp.com/tutorial/pca-analysis-r">Principal Component Analysis in R Tutorial</a></p></li>
<li><p>[- <a href="https://www.statforbiology.com/2021/stat_multivar_pca/">Principal Component Analysis in R Tutorial</a></p></li>
<li><p><a href="https://statologos.com/analisis-de-componentes-principales-en-r/">Análisis de Componentes Principales (PCA)</a></p></li>
<li><p><a href="https://rstudio-pubs-static.s3.amazonaws.com/841127_fd111ed9c6a040e1a90e92686f90e3f8.html#353_Variables_cuantitativas">Principal Component Analysis in R Tutorial</a></p></li>
<li><p><a href="https://arcruz0.github.io/libroadp/indexes.html">Análisis de componentes principales</a></p></li>
<li><p><a href="https://cienciadedatos.net/documentos/52_deteccion_anomalias_autoencoder_pca.html#Bagging_PCA">Detección de anomalías: Autoencoders y PCA</a></p></li>
<li><p><a href="https://rpubs.com/Cristina_Gil/PCA">ANÁLISIS DE COMPONENTES PRINCIPALES (PCA)</a></p></li>
<li><p><a href="http://www.sthda.com/english/articles/31-principal-component-methods-in-r-practical-guide/112-pca-principal-component-analysis-essentials/#data-standardization">PCA - Principal Component Analysis Essentials</a></p></li>
<li><p><a href="https://fastercapital.com/es/contenido/Carga-factorial--decodificacion-de-cargas-factoriales-en-el-modelo-multifactor.html#:~:text=los%20m%C3%A1s%20desafiantes.-,Las%20cargas%20factoriales%20representan%20la%20fuerza%20de%20la%20relaci%C3%B3n%20entre,como%20correlaciones%20entre%20las%20variables">Carga factorial decodificacion de cargas factoriales en el modelo multifactor</a></p></li>
</ul>
</div>
<div id="más-información" class="section level1">
<h1>Más información</h1>
<p><a name="12"></a></p>
<p>Estos análisis se han realizado utilizando el software R (v.4.3.2) y Rstudio (v. 2023.12.0)</p>
<p>Recuerda que todos nuestros códigos están almacenados en <a href="https://github.com/RBiologos/Posts">GitHub</a></p>
<center>
<img src="https://i.ibb.co/DpKmR1k/github.png" width="350" />
</center>
</div>

        </div>
        
        

<div class="social-share pt-4">
	<h4>Comparte:</h4>
	
	<a class="resp-sharing-button__link" href="https://facebook.com/sharer/sharer.php?u=https%3a%2f%2frbiologos.github.io%2fblog%2fa018%2f" target="_blank"
		rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--facebook resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path d="M18.77 7.46H14.5v-1.9c0-.9.6-1.1 1-1.1h3V.5h-4.33C10.24.5 9.5 3.44 9.5 5.32v2.15h-3v4h3v12h5v-12h3.85l.42-4z" />
				</svg>
			</div>
		</div>
	</a>

	
	<a class="resp-sharing-button__link" href="https://twitter.com/intent/tweet/?text=An%c3%a1lisis%20de%20componentes%20principales&amp;url=https%3a%2f%2frbiologos.github.io%2fblog%2fa018%2f"
		target="_blank" rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--twitter resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path
						d="M23.44 4.83c-.8.37-1.5.38-2.22.02.93-.56.98-.96 1.32-2.02-.88.52-1.86.9-2.9 1.1-.82-.88-2-1.43-3.3-1.43-2.5 0-4.55 2.04-4.55 4.54 0 .36.03.7.1 1.04-3.77-.2-7.12-2-9.36-4.75-.4.67-.6 1.45-.6 2.3 0 1.56.8 2.95 2 3.77-.74-.03-1.44-.23-2.05-.57v.06c0 2.2 1.56 4.03 3.64 4.44-.67.2-1.37.2-2.06.08.58 1.8 2.26 3.12 4.25 3.16C5.78 18.1 3.37 18.74 1 18.46c2 1.3 4.4 2.04 6.97 2.04 8.35 0 12.92-6.92 12.92-12.93 0-.2 0-.4-.02-.6.9-.63 1.96-1.22 2.56-2.14z" />
				</svg>
			</div>
		</div>
	</a>

	
	<a class="resp-sharing-button__link" href="https://plus.google.com/share?url=https%3a%2f%2frbiologos.github.io%2fblog%2fa018%2f" target="_blank"
		rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--google resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path
						d="M11.37 12.93c-.73-.52-1.4-1.27-1.4-1.5 0-.43.03-.63.98-1.37 1.23-.97 1.9-2.23 1.9-3.57 0-1.22-.36-2.3-1-3.05h.5c.1 0 .2-.04.28-.1l1.36-.98c.16-.12.23-.34.17-.54-.07-.2-.25-.33-.46-.33H7.6c-.66 0-1.34.12-2 .35-2.23.76-3.78 2.66-3.78 4.6 0 2.76 2.13 4.85 5 4.9-.07.23-.1.45-.1.66 0 .43.1.83.33 1.22h-.08c-2.72 0-5.17 1.34-6.1 3.32-.25.52-.37 1.04-.37 1.56 0 .5.13.98.38 1.44.6 1.04 1.84 1.86 3.55 2.28.87.23 1.82.34 2.8.34.88 0 1.7-.1 2.5-.34 2.4-.7 3.97-2.48 3.97-4.54 0-1.97-.63-3.15-2.33-4.35zm-7.7 4.5c0-1.42 1.8-2.68 3.9-2.68h.05c.45 0 .9.07 1.3.2l.42.28c.96.66 1.6 1.1 1.77 1.8.05.16.07.33.07.5 0 1.8-1.33 2.7-3.96 2.7-1.98 0-3.54-1.23-3.54-2.8zM5.54 3.9c.33-.38.75-.58 1.23-.58h.05c1.35.05 2.64 1.55 2.88 3.35.14 1.02-.08 1.97-.6 2.55-.32.37-.74.56-1.23.56h-.03c-1.32-.04-2.63-1.6-2.87-3.4-.13-1 .08-1.92.58-2.5zM23.5 9.5h-3v-3h-2v3h-3v2h3v3h2v-3h3" />
				</svg>
			</div>
		</div>
	</a>

	
	<a class="resp-sharing-button__link" href="mailto:?subject=An%c3%a1lisis%20de%20componentes%20principales&amp;body=https%3a%2f%2frbiologos.github.io%2fblog%2fa018%2f" target="_self"
		rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--email resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path
						d="M22 4H2C.9 4 0 4.9 0 6v12c0 1.1.9 2 2 2h20c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zM7.25 14.43l-3.5 2c-.08.05-.17.07-.25.07-.17 0-.34-.1-.43-.25-.14-.24-.06-.55.18-.68l3.5-2c.24-.14.55-.06.68.18.14.24.06.55-.18.68zm4.75.07c-.1 0-.2-.03-.27-.08l-8.5-5.5c-.23-.15-.3-.46-.15-.7.15-.22.46-.3.7-.14L12 13.4l8.23-5.32c.23-.15.54-.08.7.15.14.23.07.54-.16.7l-8.5 5.5c-.08.04-.17.07-.27.07zm8.93 1.75c-.1.16-.26.25-.43.25-.08 0-.17-.02-.25-.07l-3.5-2c-.24-.13-.32-.44-.18-.68s.44-.32.68-.18l3.5 2c.24.13.32.44.18.68z" />
				</svg>
			</div>
		</div>
	</a>

	
	<a class="resp-sharing-button__link"
		href="https://reddit.com/submit/?url=https%3a%2f%2frbiologos.github.io%2fblog%2fa018%2f&amp;resubmit=true&amp;title=An%c3%a1lisis%20de%20componentes%20principales" target="_blank"
		rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--reddit resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path
						d="M24 11.5c0-1.65-1.35-3-3-3-.96 0-1.86.48-2.42 1.24-1.64-1-3.75-1.64-6.07-1.72.08-1.1.4-3.05 1.52-3.7.72-.4 1.73-.24 3 .5C17.2 6.3 18.46 7.5 20 7.5c1.65 0 3-1.35 3-3s-1.35-3-3-3c-1.38 0-2.54.94-2.88 2.22-1.43-.72-2.64-.8-3.6-.25-1.64.94-1.95 3.47-2 4.55-2.33.08-4.45.7-6.1 1.72C4.86 8.98 3.96 8.5 3 8.5c-1.65 0-3 1.35-3 3 0 1.32.84 2.44 2.05 2.84-.03.22-.05.44-.05.66 0 3.86 4.5 7 10 7s10-3.14 10-7c0-.22-.02-.44-.05-.66 1.2-.4 2.05-1.54 2.05-2.84zM2.3 13.37C1.5 13.07 1 12.35 1 11.5c0-1.1.9-2 2-2 .64 0 1.22.32 1.6.82-1.1.85-1.92 1.9-2.3 3.05zm3.7.13c0-1.1.9-2 2-2s2 .9 2 2-.9 2-2 2-2-.9-2-2zm9.8 4.8c-1.08.63-2.42.96-3.8.96-1.4 0-2.74-.34-3.8-.95-.24-.13-.32-.44-.2-.68.15-.24.46-.32.7-.18 1.83 1.06 4.76 1.06 6.6 0 .23-.13.53-.05.67.2.14.23.06.54-.18.67zm.2-2.8c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2zm5.7-2.13c-.38-1.16-1.2-2.2-2.3-3.05.38-.5.97-.82 1.6-.82 1.1 0 2 .9 2 2 0 .84-.53 1.57-1.3 1.87z" />
				</svg>
			</div>
		</div>
	</a>

	
	<a class="resp-sharing-button__link" href="whatsapp://send?text=An%c3%a1lisis%20de%20componentes%20principales%20https%3a%2f%2frbiologos.github.io%2fblog%2fa018%2f" target="_blank"
		rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--whatsapp resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path
						d="M20.1 3.9C17.9 1.7 15 .5 12 .5 5.8.5.7 5.6.7 11.9c0 2 .5 3.9 1.5 5.6L.6 23.4l6-1.6c1.6.9 3.5 1.3 5.4 1.3 6.3 0 11.4-5.1 11.4-11.4-.1-2.8-1.2-5.7-3.3-7.8zM12 21.4c-1.7 0-3.3-.5-4.8-1.3l-.4-.2-3.5 1 1-3.4L4 17c-1-1.5-1.4-3.2-1.4-5.1 0-5.2 4.2-9.4 9.4-9.4 2.5 0 4.9 1 6.7 2.8 1.8 1.8 2.8 4.2 2.8 6.7-.1 5.2-4.3 9.4-9.5 9.4zm5.1-7.1c-.3-.1-1.7-.9-1.9-1-.3-.1-.5-.1-.7.1-.2.3-.8 1-.9 1.1-.2.2-.3.2-.6.1s-1.2-.5-2.3-1.4c-.9-.8-1.4-1.7-1.6-2-.2-.3 0-.5.1-.6s.3-.3.4-.5c.2-.1.3-.3.4-.5.1-.2 0-.4 0-.5C10 9 9.3 7.6 9 7c-.1-.4-.4-.3-.5-.3h-.6s-.4.1-.7.3c-.3.3-1 1-1 2.4s1 2.8 1.1 3c.1.2 2 3.1 4.9 4.3.7.3 1.2.5 1.6.6.7.2 1.3.2 1.8.1.6-.1 1.7-.7 1.9-1.3.2-.7.2-1.2.2-1.3-.1-.3-.3-.4-.6-.5z" />
				</svg>
			</div>
		</div>
	</a>
	
	<a class="resp-sharing-button__link" href="https://telegram.me/share/url?text=An%c3%a1lisis%20de%20componentes%20principales&amp;url=https%3a%2f%2frbiologos.github.io%2fblog%2fa018%2f"
		target="_blank" rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--telegram resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path
						d="M.707 8.475C.275 8.64 0 9.508 0 9.508s.284.867.718 1.03l5.09 1.897 1.986 6.38a1.102 1.102 0 0 0 1.75.527l2.96-2.41a.405.405 0 0 1 .494-.013l5.34 3.87a1.1 1.1 0 0 0 1.046.135 1.1 1.1 0 0 0 .682-.803l3.91-18.795A1.102 1.102 0 0 0 22.5.075L.706 8.475z" />
				</svg>
			</div>
		</div>
	</a>

</div>
        
        
        <div class="mt-5">
          
        </div>
      </div>
    </div>
  </div>
</section>


  </div><!-- end Contact Area -->
<footer id="footer" class="section-bg">
	<div class="container">
		<div class="row wow fadeInUp" data-wow-duration="500ms">
			<div class="col-lg-12">

			

                        <!-- Footer Social Links -->
				<div class="social-icon"><h1><center                                                    >Social</center></h1>
					<ul class="list-inline">
						
						<li class="list-inline-item"><a href="https://www.youtube.com/channel/UC0IBjs0-Qg5h5p-rqwT7c7w" target="blank"><i class="ti-youtube" target="blank"></i></a></li>
						
						<li class="list-inline-item"><a href="https://www.instagram.com/rbiologos/" target="blank"><i class="ti-instagram" target="blank"></i></a></li>
						
						<li class="list-inline-item"><a href="https://www.facebook.com/rbiologos" target="blank"><i class="ti-facebook" target="blank"></i></a></li>
						
						<li class="list-inline-item"><a href="https://github.com/RBiologos/Posts" target="blank"><i class="ti-github" target="blank"></i></a></li>
						
					</ul>
				</div>
				
				<center><img src="https://i.ibb.co/4RJbzB6/2.png" alt="R Biólogos" height="150" /></center>
	
				<!-- copyright -->
				<div class="copyright text-center">
				        
					<a href="https://rbiologos.github.io/">
					</a>
					<br>
					<p1></p1>
				</div>
				
			</div>
		</div>
	</div>
</footer>
<!-- /footer -->

<!-- Google Map API -->


<!-- JS Plugins -->

<script src="https://rbiologos.github.io/plugins/jquery/jquery.min.js"></script>

<script src="https://rbiologos.github.io/plugins/bootstrap/bootstrap.min.js"></script>

<script src="https://rbiologos.github.io/plugins/slick/slick.min.js"></script>

<script src="https://rbiologos.github.io/plugins/shuffle/shuffle.min.js"></script>

<script src="https://rbiologos.github.io/plugins/magnific-popup/jquery.magnific-popup.min.js"></script>

<script src="https://rbiologos.github.io/plugins/lazy-load/lozad.min.js"></script>

<script src="https://rbiologos.github.io/plugins/google-map/map.js"></script>


<!-- Main Script -->

<script src="https://rbiologos.github.io/js/script.min.ab3836b70bc45170e8ff6dd572ee5e8e761ac8376daf9ceb40f760dfb6f2cce49672517da770a0049959f5fc93337e13.js" integrity="sha384-qzg2twvEUXDo/23Vcu5ejnYayDdtr5zrQPdg37byzOSWclF9p3CgBJlZ9fyTM34T"></script>



<script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.1/js.cookie.min.js"></script>
<div id="js-cookie-box" class="cookie-box cookie-box-hide">
	This site uses cookies. By continuing to use this website, you agree to their use. <span id="js-cookie-button" class="btn btn-transparent">I Accept</span>
</div>
<script>
	(function ($) {
		const cookieBox = document.getElementById('js-cookie-box');
		const cookieButton = document.getElementById('js-cookie-button');
		if (!Cookies.get('cookie-box')) {
			cookieBox.classList.remove('cookie-box-hide');
			cookieButton.onclick = function () {
				Cookies.set('cookie-box', true, {
					expires:  2 
				});
				cookieBox.classList.add('cookie-box-hide');
			};
		}
	})(jQuery);
</script>
</body>

</html>
